apiVersion: v1
kind: Service
metadata:
  name: nodejs-load-balancer
  # namespace: application
spec:
  type: LoadBalancer
  selector:
    app: myapp_nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
